- name: Install packages
  notify: Restart saslauthd
  ansible.builtin.apt:
    name:
      - "sasl2-bin"
      - "libsasl2-modules"
  notify: Restart saslauthd

- name: Configure saslauthd daemon startup
  notify: Restart saslauthd
  ansible.builtin.lineinfile:
    path: "/etc/default/saslauthd"
    search_string: "{{ item.param }}="
    line: "{{ item.param }}={{ item.value }}"
  loop:
    - param: "START"
      value: "yes"
    - param: "MECHANISMS"
      value: "{{ saslauthd_mechanism }}"
    - param: "MECH_OPTIONS"
      value: "{{ saslauthd_mech_options }}"
    - param: "THREADS"
      value: "{{ saslauthd_threads }}"
    - param: "OPTIONS"
      value: "{{ saslauthd_options }}"

- name: Configure "ldap" mechanism
  when: "'ldap' in saslauthd_mechanism"
  notify: Restart saslauthd
  block:
    - name: Install ca-certificates package
      ansible.builtin.apt:
        name:
          - "ca-certificates"
    - name: Create /etc/ldap directory
      ansible.builtin.file:
        dest: "/etc/ldap"
        state: "directory"
        mode: "0755"
    - name: Create /etc/ldap/ldap.conf file
      ansible.builtin.template:
        src: "templates/ldap.conf"
        dest: "/etc/ldap/ldap.conf"
        mode: "0644"
    - name: Create /etc/saslauthd.conf file
      ansible.builtin.template:
        src: "templates/saslauthd.conf"
        dest: "/etc/saslauthd.conf"
        mode: "0644"
